### ISSUE TITLE
Cannot install conda-runtime on Ubuntu 20.04 using Conda/Mamba

### ISSUE THREAD

**Issue by sjperkins** [coiled/coiled-runtime#21]
I've been trying to install the conda-runtime on Ubuntu 20.04 but run into the following issues when trying to install it in a Python 3.8 conda environment 

## Conda

```
$ conda create -n crt
$ conda activate crt
(crt) $ conda install -c coiled coiled-runtime
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                     

UnsatisfiableError: 

(crt) $ python
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import coiled
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'coiled'
>>> 
```

## Mamba

```
$ mamba create -n crt
$ mamba activate crt
(crt) $ mamba install -c coiled coiled-runtime

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['coiled-runtime']

pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
coiled/linux-64          [====================] (00m:00s) No change
coiled/noarch            [====================] (00m:00s) No change
Encountered problems while solving:
  - nothing provides coiled needed by coiled-runtime-0.0.3-py_0

(crt) simon@sjp-tpe15:~$ python
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import coiled
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'coiled'
>>> 
```

**Comment by dchudz** [comment]
Is `coiled` the only package in there that we need conda-forge for?

Can we specify that `coiled` comes from pip instead, to avoid users needing that setup?

**Comment by sjperkins** [comment]
Thanks @ncclementi, indeed I was doing something dumb with conda as I suspected. I've created a PR describing conda-forge `README.rst` for the conda-illiterate.

**Comment by jrbourbeau** [comment]
How about `conda install -c coiled -c conda-forge coiled-runtime` instead? @sjperkins does that fix the issue you're seeing?

**Comment by sjperkins** [comment]
> How about `conda install -c coiled -c conda-forge coiled-runtime` instead? @sjperkins does that fix the issue you're seeing?

Yes, this works locally for me.

**Comment by jrbourbeau** [comment]
Great, let's go with that then over in https://github.com/coiled/coiled-runtime/pull/23 since it's less intrusive / doesn't involve updating user's conda config settings
