### ISSUE TITLE
Regression with `test_anom_mean` and `test_basic_sum`

### ISSUE THREAD

**Issue by j-bennet** [coiled/coiled-runtime#742]
```
Traceback (most recent call last):
  File "/home/runner/work/coiled-runtime/coiled-runtime/detect_regressions.py", line 139, in <module>
    regressions_report(regressions_df)
  File "/home/runner/work/coiled-runtime/coiled-runtime/detect_regressions.py", line 126, in regressions_report
    raise Exception(
Exception:  Regressions detected 2: 
runtime = 'coiled-0.2.1-py3.9', name = 'test_anom_mean[uncompressible]', category = 'benchmarks', last_three_duration [s] = (65.1[15](https://github.com/coiled/coiled-runtime/actions/runs/4516386672/jobs/7955215570#step:5:16)14854431152, 62.95351457595825, 65.6007709503[17](https://github.com/coiled/coiled-runtime/actions/runs/4516386672/jobs/7955215570#step:5:18)38), duration_threshold [s] = 61.5528497433[18](https://github.com/coiled/coiled-runtime/actions/runs/4516386672/jobs/7955215570#step:5:19)67 
runtime = 'coiled-0.2.1-py3.9', name = 'test_basic_sum[slow-thin]', category = 'benchmarks', last_three_duration [s] = (176.3395631313324, 173.[20](https://github.com/coiled/coiled-runtime/actions/runs/4516386672/jobs/7955215570#step:5:21)296263694763, 180.05609250068665), duration_threshold [s] = 172.62236283408234
```

Workflow:

* https://github.com/coiled/coiled-runtime/actions/runs/4516386672

**Comment by crusaderky** [comment]
>@crusaderky did you change anything in the test logic that would explain a bit more variance?

No, `uncompressible` is identical to before the addition to `compressible`.
